version: '3'
services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - api
  api:
    restart: always
    build: ./api
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./api/data:/data/db
    ports:
      - '27017:27017'
